# Not really used right now but if we ever do some auto-generation/verification
# of things then we can use travis for that.

language: bash
arch: arm64-graviton2
virt: vm
dist: focal
group: edge


services:
  - docker

before_install:

script:
  tools/verify-all.sh
